name: Changed rust files

description: "Any changed rust files"

outputs:
  any_changed:
    description: "Any changed rust files"
    value: ${{ steps.changed-rust-files.outputs.any_changed }}

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ${{ github.repository }}
        fetch-depth: 0
    - name: Get changed rust files
      id: changed-rust-files
      uses: tj-actions/changed-files@v18.7
      with:
        files: |
          **/*.rs
          Cargo.toml
          Cargo.lock
