name: Changed rust files

on:
  workflow_call:
    outputs:
      any_changed:
        description: "Any changed rust files"
        value: ${{ jobs.rust-files.outputs.any_changed }}

jobs:
  rust-files:
      runs-on: ubuntu-latest
      outputs:
        any_changed: ${{ steps.changed-rust-files.outputs.any_changed }}
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed rust files
        id: changed-rust-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            **/*.rs
            Cargo.toml
            Cargo.lock
